In [2]:
import pandas as pd

In [24]:
df = pd.read_csv('teste2.csv')

df.pop('poster_url')
df.pop('movieId')
df.pop('title')
df.pop('year')

df

                                           genres
0     Adventure|Animation|Children|Comedy|Fantasy
1                      Adventure|Children|Fantasy
2                                  Comedy|Romance
3                            Comedy|Drama|Romance
4                                          Comedy
...                                           ...
9703              Action|Animation|Comedy|Fantasy
9704                     Animation|Comedy|Fantasy
9705                                        Drama
9706                             Action|Animation
9707                                       Comedy

[9708 rows x 1 columns]

In [38]:
df.loc[:, 'genres']

df_genero = pd.DataFrame(columns=['genero'])


def alinhando(string, df_ajustado):
    dividindo = string.split('|')
    df_novos = pd.DataFrame({'genero': dividindo})

    # 2. Concatenamos os dois
    df_ajustado = pd.concat([df_ajustado, df_novos], ignore_index=True)

    return df_ajustado


        
df_genero = alinhando('Adventure|Animation|Children|Comedy|Fantasy', df_genero)

df_genero

      genero
0  Adventure
1  Animation
2   Children
3     Comedy
4    Fantasy

In [51]:
def extrair_generos(string):
    if pd.isna(string):
        return []
    return string.split('|')

# 2. Aplicando a função na coluna 'genres'
# Isso criará uma coluna onde cada linha contém uma lista: ['Adventure', 'Animation', ...]
df['generos_lista'] = df['genres'].apply(extrair_generos)

# 3. O "Pulo do Gato": Usar o explode para transformar cada item da lista em uma nova linha
df_genero = df[['generos_lista']].explode('generos_lista')

# 4. Ajustar nomes e remover duplicatas (opcional)
df_genero.columns = ['genero']
df_genero = df_genero.reset_index(drop=True)

df_genero

          genero
0      Adventure
1      Animation
2       Children
3         Comedy
4        Fantasy
...          ...
22045    Fantasy
22046      Drama
22047     Action
22048  Animation
22049     Comedy

[22050 rows x 1 columns]

In [52]:
unicos = df_genero['genero'].unique()

unicos

<StringArray>
[  'Adventure',   'Animation',    'Children',      'Comedy',     'Fantasy',
     'Romance',       'Drama',      'Action',       'Crime',    'Thriller',
      'Horror',     'Mystery',      'Sci-Fi',         'War',     'Musical',
 'Documentary',        'IMAX',     'Western',   'Film-Noir']
Length: 19, dtype: str